version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: appveyor-retry dotnet restore -v Minimal
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
before_package:
- cmd: >-
    dotnet build Bara -c %CONFIGURATION%

    dotnet build Bara.Test -c %CONFIGURATION%
after_build:
- cmd: dotnet pack Bara -c %CONFIGURATION%
test: off
artifacts:
- path: .\Release\Bara.*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: mrmWrcj0pCn8uj6Qtw9ML5Ac7HV0JddDxvGrBPX4x2boxdx1IvC1/kaMJpmvIOsBZa0cIz4iFuhF/OYzLvC2F4hIIxEr7lB8pW4HXmncUo8=
  skip_symbols: true
  artifact: /.*\.nupkg/