version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
matrix:
  fast_finish: true
before_build:
- cmd: >-
    cd Dev

    appveyor-retry dotnet restore -v Minimal
build:
  publish_nuget: true
  include_nuget_references: true
  parallel: true
  verbosity: normal
before_package:
- cmd: >-
    dotnet build Bara -c %CONFIGURATION% --output 'bin\Release\'
test: off
artifacts:
- path: 'Bara\bin\Release\Bara.*.nupkg'
  name: BaraNupkg
deploy:
- provider: NuGet
  api_key:
    secure: 6rz3S9gGcjrpLeXVMcsvxPfqMV6ME2qyY0op6lh7Bn/4O9VN3TItSDv9aEvpNMrB
  skip_symbols: true
  artifact: /.*\.nupkg/